/* Indicator registry — mirrors Indicator_Formula_Register.xlsx exactly */
const INDICATORS = [
  {
    id: "I01",
    domain: "Cost",
    name: "Cost Growth %",
    unit: "%",
    dir: "asc",
    anchors: [0, 0.02, 0.05, 0.1, 0.2],
    formula: "(Current Budget − Baseline Budget) / Baseline Budget",
    source: "source",
    raw: (p) => (p.current_budget - p.baseline_budget) / p.baseline_budget,
  },
  {
    id: "I02",
    domain: "Cost",
    name: "EAC Variance %",
    unit: "%",
    dir: "asc",
    anchors: [0, 0.03, 0.07, 0.12, 0.2],
    formula: "(EAC − Current Budget) / Current Budget",
    source: "source",
    raw: (p) => (p.eac - p.current_budget) / p.current_budget,
  },
  {
    id: "I03",
    domain: "Cost",
    name: "Contingency Drawdown %",
    unit: "%",
    dir: "asc",
    anchors: [0, 0.4, 0.65, 0.85, 1.0],
    formula: "Contingency Used / Original Contingency",
    source: "source",
    raw: (p) => p.contingency_used / p.contingency_original,
  },
  {
    id: "I04",
    domain: "Schedule",
    name: "Finish-Date Slip",
    unit: "days",
    dir: "asc",
    anchors: [0, 15, 30, 60, 120],
    formula: "Current Forecast Finish − Baseline Finish",
    source: "source",
    raw: (p) =>
      Math.round(
        (new Date(p.current_finish) - new Date(p.baseline_finish)) / 86400000,
      ),
  },
  {
    id: "I05",
    domain: "Schedule",
    name: "Float Erosion",
    unit: "days",
    dir: "asc",
    anchors: [0, 5, 10, 20, 40],
    formula: "Baseline Total Float − Current Total Float",
    source: "source",
    raw: (p) => p.baseline_float - p.current_float,
  },
  {
    id: "I06",
    domain: "Schedule",
    name: "Milestone Compliance %",
    unit: "%",
    dir: "desc",
    anchors: [1.0, 0.9, 0.8, 0.65, 0.5],
    formula: "Milestones Achieved On/Before Planned Date / Milestones Due",
    source: "source",
    raw: (p) => p.milestones_on_time / p.milestones_due,
  },
  {
    id: "I07",
    domain: "Change",
    name: "Pending Change Exposure %",
    unit: "%",
    dir: "asc",
    anchors: [0, 0.02, 0.05, 0.1, 0.2],
    formula: "Pending Change Value / Current Budget",
    source: "source",
    raw: (p) => p.pending_change_value / p.current_budget,
  },
  {
    id: "I08",
    domain: "Change",
    name: "Change Aging",
    unit: "days",
    dir: "asc",
    anchors: [0, 30, 60, 90, 180],
    formula: "Average (Current Date − Date Raised) across open changes",
    source: "source",
    raw: (p) => p.avg_change_aging,
  },
  {
    id: "I10",
    domain: "Risk",
    name: "Aggregate Risk Exposure Ratio %",
    unit: "%",
    dir: "asc",
    anchors: [0, 0.03, 0.07, 0.15, 0.25],
    formula:
      "Sum of (Probability × Cost Impact) for open risks / Current Budget",
    source: "addition",
    raw: (p) => p.sum_open_risk_exposure / p.current_budget,
  },
  {
    id: "I11",
    domain: "Risk",
    name: "Mitigation Overdue %",
    unit: "%",
    dir: "asc",
    anchors: [0, 0.1, 0.25, 0.5, 0.75],
    formula: "Overdue Open Mitigation Actions / Open Mitigation Actions",
    source: "source",
    raw: (p) =>
      p.open_mitigation === 0 ? 0 : p.overdue_mitigation / p.open_mitigation,
  },
  {
    id: "I12",
    domain: "Contractor Performance",
    name: "Contractor Schedule Compliance %",
    unit: "%",
    dir: "desc",
    anchors: [1.0, 0.9, 0.75, 0.6, 0.4],
    formula: "Compliant Schedule Submissions / Required Submissions",
    source: "source",
    raw: (p) =>
      p.required_submissions === 0
        ? 1
        : p.compliant_submissions / p.required_submissions,
  },
  {
    id: "I13",
    domain: "Constructability",
    name: "Unresolved High-Severity Issue Rate %",
    unit: "%",
    dir: "asc",
    anchors: [0, 0.15, 0.3, 0.5, 0.75],
    formula: "High-Severity Open Issues / Total Open Issues",
    source: "addition",
    raw: (p) =>
      p.open_issues === 0 ? 0 : p.high_severity_issues / p.open_issues,
  },
  {
    id: "I14",
    domain: "Constructability",
    name: "Average Issue Aging",
    unit: "days",
    dir: "asc",
    anchors: [0, 20, 40, 70, 120],
    formula: "Average (Current Date − Date Identified) across open issues",
    source: "addition",
    raw: (p) => p.avg_issue_aging,
  },
  {
    id: "I15",
    domain: "Sequencing/Interfaces",
    name: "Interface Conflict Rate %",
    unit: "%",
    dir: "asc",
    anchors: [0, 0.1, 0.25, 0.45, 0.7],
    formula: "Unresolved Sequencing/Interface Conflicts / Active Interfaces",
    source: "source",
    raw: (p) =>
      p.active_interfaces === 0
        ? 0
        : p.unresolved_conflicts / p.active_interfaces,
  },
];

const DOMAINS = [
  { name: "Cost", weight: 0.2, indicators: ["I01", "I02", "I03"] },
  { name: "Schedule", weight: 0.2, indicators: ["I04", "I05", "I06"] },
  { name: "Risk", weight: 0.15, indicators: ["I10", "I11"] },
  { name: "Change", weight: 0.15, indicators: ["I07", "I08"] },
  { name: "Contractor Performance", weight: 0.1, indicators: ["I12"] },
  { name: "Constructability", weight: 0.1, indicators: ["I13", "I14"] },
  { name: "Sequencing/Interfaces", weight: 0.1, indicators: ["I15"] },
];

const FIELD_LABELS = {
  baseline_budget: ["Cost", "Baseline Budget", "USD"],
  current_budget: ["Cost", "Current Budget", "USD"],
  eac: ["Cost", "Estimate at Completion (EAC)", "USD"],
  contingency_original: ["Cost", "Contingency — Original", "USD"],
  contingency_used: ["Cost", "Contingency — Used", "USD"],
  baseline_finish: ["Schedule", "Baseline Finish", "date"],
  current_finish: ["Schedule", "Current Forecast Finish", "date"],
  baseline_float: ["Schedule", "Baseline Total Float", "days"],
  current_float: ["Schedule", "Current Total Float", "days"],
  milestones_due: ["Schedule", "Milestones Due", "count"],
  milestones_on_time: ["Schedule", "Milestones Achieved On Time", "count"],
  pending_change_value: ["Change", "Pending Change Value", "USD"],
  avg_change_aging: ["Change", "Average Change Aging", "days"],
  sum_open_risk_exposure: ["Risk", "Sum of Open Risk Exposure", "USD"],
  open_mitigation: ["Risk", "Open Mitigation Actions", "count"],
  overdue_mitigation: ["Risk", "Overdue Mitigation Actions", "count"],
  required_submissions: [
    "Contractor Performance",
    "Required Submissions",
    "count",
  ],
  compliant_submissions: [
    "Contractor Performance",
    "Compliant Submissions",
    "count",
  ],
  open_issues: ["Constructability", "Open Constructability Issues", "count"],
  high_severity_issues: [
    "Constructability",
    "High-Severity Open Issues",
    "count",
  ],
  avg_issue_aging: ["Constructability", "Average Issue Aging", "days"],
  active_interfaces: ["Sequencing/Interfaces", "Active Interfaces", "count"],
  unresolved_conflicts: [
    "Sequencing/Interfaces",
    "Unresolved Conflicts",
    "count",
  ],
};

/* SYNTHETIC PORTFOLIO — verified against Indicator_Formula_Register.xlsx */
const PROJECTS_SEED = [
  {
    id: "SYN-001",
    name: "Riverside Station Platform Rehabilitation",
    archetype: "Reused from the Formula Register worked example",
    baseline_budget: 18400000,
    current_budget: 18400000,
    eac: 19900000,
    contingency_original: 1840000,
    contingency_used: 1122400,
    baseline_finish: "2027-06-15",
    current_finish: "2027-07-10",
    baseline_float: 22,
    current_float: 6,
    milestones_due: 4,
    milestones_on_time: 3,
    pending_change_value: 650000,
    avg_change_aging: 45,
    sum_open_risk_exposure: 780000,
    open_mitigation: 9,
    overdue_mitigation: 2,
    required_submissions: 12,
    compliant_submissions: 9,
    open_issues: 6,
    high_severity_issues: 2,
    avg_issue_aging: 35,
    active_interfaces: 8,
    unresolved_conflicts: 2,
  },
  {
    id: "SYN-002",
    name: "Northline Signal House Replacement",
    archetype: "Stable / low risk across all domains",
    baseline_budget: 9200000,
    current_budget: 9200000,
    eac: 9350000,
    contingency_original: 920000,
    contingency_used: 180000,
    baseline_finish: "2027-04-01",
    current_finish: "2027-04-06",
    baseline_float: 18,
    current_float: 15,
    milestones_due: 3,
    milestones_on_time: 3,
    pending_change_value: 90000,
    avg_change_aging: 12,
    sum_open_risk_exposure: 140000,
    open_mitigation: 4,
    overdue_mitigation: 0,
    required_submissions: 8,
    compliant_submissions: 8,
    open_issues: 1,
    high_severity_issues: 0,
    avg_issue_aging: 8,
    active_interfaces: 3,
    unresolved_conflicts: 0,
  },
  {
    id: "SYN-003",
    name: "Bay Junction Track Renewal",
    archetype: "Cost-driven",
    baseline_budget: 24000000,
    current_budget: 25400000,
    eac: 27800000,
    contingency_original: 2400000,
    contingency_used: 2050000,
    baseline_finish: "2027-09-01",
    current_finish: "2027-09-20",
    baseline_float: 20,
    current_float: 14,
    milestones_due: 5,
    milestones_on_time: 4,
    pending_change_value: 1100000,
    avg_change_aging: 50,
    sum_open_risk_exposure: 1500000,
    open_mitigation: 10,
    overdue_mitigation: 3,
    required_submissions: 10,
    compliant_submissions: 8,
    open_issues: 4,
    high_severity_issues: 1,
    avg_issue_aging: 25,
    active_interfaces: 6,
    unresolved_conflicts: 1,
  },
  {
    id: "SYN-004",
    name: "Harbor Yard Maintenance Facility Upgrade",
    archetype: "Contractor-driven",
    baseline_budget: 15600000,
    current_budget: 15600000,
    eac: 16100000,
    contingency_original: 1560000,
    contingency_used: 500000,
    baseline_finish: "2027-05-15",
    current_finish: "2027-06-02",
    baseline_float: 16,
    current_float: 9,
    milestones_due: 6,
    milestones_on_time: 3,
    pending_change_value: 300000,
    avg_change_aging: 20,
    sum_open_risk_exposure: 400000,
    open_mitigation: 6,
    overdue_mitigation: 1,
    required_submissions: 14,
    compliant_submissions: 6,
    open_issues: 2,
    high_severity_issues: 0,
    avg_issue_aging: 15,
    active_interfaces: 4,
    unresolved_conflicts: 0,
  },
  {
    id: "SYN-005",
    name: "Elm Street Pedestrian Bridge Rehabilitation",
    archetype: "Constructability-driven",
    baseline_budget: 11200000,
    current_budget: 11200000,
    eac: 11500000,
    contingency_original: 1120000,
    contingency_used: 300000,
    baseline_finish: "2027-03-01",
    current_finish: "2027-03-15",
    baseline_float: 25,
    current_float: 20,
    milestones_due: 4,
    milestones_on_time: 4,
    pending_change_value: 200000,
    avg_change_aging: 15,
    sum_open_risk_exposure: 250000,
    open_mitigation: 5,
    overdue_mitigation: 0,
    required_submissions: 8,
    compliant_submissions: 8,
    open_issues: 9,
    high_severity_issues: 5,
    avg_issue_aging: 55,
    active_interfaces: 3,
    unresolved_conflicts: 0,
  },
  {
    id: "SYN-006",
    name: "Central Junction Interlocking Renewal",
    archetype: "Compound — multiple domains simultaneously",
    baseline_budget: 32000000,
    current_budget: 34500000,
    eac: 39000000,
    contingency_original: 3200000,
    contingency_used: 3050000,
    baseline_finish: "2027-11-01",
    current_finish: "2028-01-10",
    baseline_float: 15,
    current_float: -5,
    milestones_due: 6,
    milestones_on_time: 2,
    pending_change_value: 2800000,
    avg_change_aging: 95,
    sum_open_risk_exposure: 3200000,
    open_mitigation: 14,
    overdue_mitigation: 7,
    required_submissions: 16,
    compliant_submissions: 9,
    open_issues: 8,
    high_severity_issues: 4,
    avg_issue_aging: 80,
    active_interfaces: 10,
    unresolved_conflicts: 4,
  },
  {
    id: "SYN-007",
    name: "Meridian Yard Interlocking Interface Package",
    archetype: "Sequencing-driven",
    baseline_budget: 8700000,
    current_budget: 8700000,
    eac: 8950000,
    contingency_original: 870000,
    contingency_used: 350000,
    baseline_finish: "2027-02-01",
    current_finish: "2027-02-20",
    baseline_float: 12,
    current_float: 5,
    milestones_due: 3,
    milestones_on_time: 2,
    pending_change_value: 150000,
    avg_change_aging: 25,
    sum_open_risk_exposure: 200000,
    open_mitigation: 5,
    overdue_mitigation: 1,
    required_submissions: 6,
    compliant_submissions: 6,
    open_issues: 2,
    high_severity_issues: 0,
    avg_issue_aging: 10,
    active_interfaces: 9,
    unresolved_conflicts: 5,
  },
  {
    id: "SYN-008",
    name: "Fairview Avenue Grade Crossing Improvements",
    archetype: "Change-driven",
    baseline_budget: 6400000,
    current_budget: 6400000,
    eac: 6550000,
    contingency_original: 640000,
    contingency_used: 210000,
    baseline_finish: "2027-06-01",
    current_finish: "2027-06-12",
    baseline_float: 20,
    current_float: 16,
    milestones_due: 3,
    milestones_on_time: 3,
    pending_change_value: 950000,
    avg_change_aging: 110,
    sum_open_risk_exposure: 180000,
    open_mitigation: 4,
    overdue_mitigation: 1,
    required_submissions: 6,
    compliant_submissions: 6,
    open_issues: 1,
    high_severity_issues: 0,
    avg_issue_aging: 10,
    active_interfaces: 2,
    unresolved_conflicts: 0,
  },
];